import type { BehavioralFramework } from '../../types/content'

export const behavioralFrameworks: BehavioralFramework[] = [
  {
    id: 'tell-me-about-yourself',
    question: 'Tell me about yourself.',
    themes: ['intro', 'positioning'],
    situation: 'Backend engineer with 5+ years working on Python services, distributed systems and product-facing backend platforms.',
    task: 'Give a focused narrative that connects experience to the role instead of reciting the whole CV.',
    action: [
      'Open with current backend identity: Python, APIs, data-intensive systems and ownership.',
      'Mention strongest proof points: FastAPI, PostgreSQL, AWS, Kafka/RabbitMQ, Kubernetes and observability.',
      'Bridge to the company: complex product logic, reliability and user-visible backend impact.',
    ],
    result: 'The interviewer should remember a backend engineer who can ship product features and handle scale/reliability when the product needs it.',
    adaptByCompany: 'For Abacum, emphasize finance-data trust, calculation correctness, integrations and the FastAPI-to-Django refresh plan.',
  },
  {
    id: 'why-this-company',
    question: 'Why this company?',
    themes: ['motivation', 'company-fit'],
    situation: 'The company solves a real workflow problem with backend depth and domain complexity.',
    task: 'Show specific interest without sounding like generic startup enthusiasm.',
    action: [
      'Name the product problem in your own words.',
      'Connect it to backend challenges you enjoy.',
      'Mention one company-specific signal from the process or product.',
    ],
    result: 'A credible answer that says you understand the product and the engineering work behind it.',
    adaptByCompany: 'For Abacum, talk about replacing spreadsheet-heavy FP&A workflows with reliable real-time planning and AI-native tooling.',
  },
  {
    id: 'why-role',
    question: 'Why are you interested in this role?',
    themes: ['motivation', 'role-fit'],
    situation: 'The role combines product backend, complex business logic and architecture evolution.',
    task: 'Explain why this is a natural next step from previous platform and distributed-systems work.',
    action: [
      'Connect product feature delivery with system quality.',
      'Explain that you want ownership, not only ticket execution.',
      'Acknowledge the Django refresh directly and positively.',
    ],
    result: 'The role feels like a deliberate fit for strengths and growth areas.',
    adaptByCompany: 'For Abacum, say Python/Django product backend plus FP&A calculation logic is the attractive center of gravity.',
  },
  {
    id: 'technical-decision-led',
    question: 'Tell me about a technical decision you led.',
    themes: ['ownership', 'technical-leadership'],
    situation: 'A high-throughput platform needed a more scalable event architecture.',
    task: 'Evaluate RabbitMQ limitations and propose a migration path that reduced risk.',
    action: [
      'Gathered throughput, reliability and operational pain points.',
      'Compared options using ordering, replay, consumer scaling and operational maturity.',
      'Proposed incremental migration with idempotent consumers, observability and rollback.',
    ],
    result: 'The team got a clearer architecture path and a safer migration strategy.',
    adaptByCompany: 'Tie the decision style to Abacum architecture evolution: measure first, migrate incrementally, keep product reliability central.',
  },
  {
    id: 'conflict-disagreement',
    question: 'Tell me about a conflict or disagreement.',
    themes: ['collaboration', 'judgment'],
    situation: 'A product or technical stakeholder wanted speed while engineering saw reliability or maintainability risk.',
    task: 'Resolve the disagreement without making it personal.',
    action: [
      'Restated the shared goal.',
      'Separated reversible and irreversible decisions.',
      'Proposed a smaller first release plus follow-up hardening work.',
    ],
    result: 'The team shipped value while protecting the most important technical risks.',
    adaptByCompany: 'For Abacum, frame this around financial-data trust: fast is good, but silent wrong numbers are unacceptable.',
  },
  {
    id: 'production-issue',
    question: 'Tell me about a production issue.',
    themes: ['incident', 'ownership'],
    situation: 'A backend service or pipeline degraded under load or produced incorrect behavior.',
    task: 'Restore service, communicate clearly and prevent recurrence.',
    action: [
      'Triage impact and establish a timeline.',
      'Use logs, metrics and traces to isolate the failing path.',
      'Apply a minimal mitigation first, then write a postmortem and follow-up fixes.',
    ],
    result: 'Service recovered and the system gained better alerts, tests or guardrails.',
    adaptByCompany: 'Use an example involving data pipelines, event processing or API performance if possible.',
  },
  {
    id: 'technical-debt',
    question: 'Tell me about technical debt.',
    themes: ['quality', 'tradeoffs'],
    situation: 'A code path became harder to extend due to rushed delivery, unclear boundaries or missing tests.',
    task: 'Prioritize debt based on product risk rather than personal preference.',
    action: [
      'Quantified the cost: incidents, slow delivery, unclear ownership or performance.',
      'Proposed a staged cleanup tied to upcoming product work.',
      'Added tests before refactoring high-risk logic.',
    ],
    result: 'The team improved maintainability without stopping product delivery.',
    adaptByCompany: 'For Abacum, emphasize debt around calculation correctness, query performance or integration reliability.',
  },
  {
    id: 'working-with-product',
    question: 'Tell me about working with product.',
    themes: ['product', 'communication'],
    situation: 'A backend implementation had product trade-offs: scope, latency, data freshness or edge cases.',
    task: 'Translate technical constraints into product choices.',
    action: [
      'Explained options in user/business terms.',
      'Made hidden edge cases visible early.',
      'Proposed a first version with clear limitations and metrics.',
    ],
    result: 'Product made an informed decision and engineering delivered predictably.',
    adaptByCompany: 'Use finance examples: stale vs fresh data, exact vs approximate totals, sync vs async recalculation.',
  },
  {
    id: 'learning-new-tech',
    question: 'Tell me about learning a new technology quickly.',
    themes: ['learning', 'adaptability'],
    situation: 'You had to become productive in a new backend tool, cloud service or AI integration.',
    task: 'Learn enough to ship safely, not just read documentation.',
    action: [
      'Built a small spike to test the risky part.',
      'Read official docs and examples around production constraints.',
      'Pair-reviewed design assumptions with teammates.',
    ],
    result: 'The technology was integrated with clearer risks and a path to production.',
    adaptByCompany: 'Use Django refresh as the forward-looking version: strong Python base, focused ORM/transactions/testing practice.',
  },
  {
    id: 'rabbitmq-kafka-migration',
    question: 'Tell me about your RabbitMQ to Kafka migration.',
    themes: ['kafka', 'architecture', 'cv-defense'],
    situation: 'A high-throughput platform needed better event streaming characteristics.',
    task: 'Propose or lead migration while protecting existing consumers.',
    action: [
      'Analyzed RabbitMQ pain points and Kafka fit.',
      'Defined partitioning, consumer groups, idempotency and observability concerns.',
      'Planned incremental rollout with dual-running or bridging.',
    ],
    result: 'The migration proposal reduced risk and positioned the platform for higher throughput and replayability.',
    adaptByCompany: 'Connect to integration/recalculation workflows, but avoid forcing Kafka where a simple queue is enough.',
  },
  {
    id: 'mcp-rag-project',
    question: 'Tell me about your MCP/RAG project.',
    themes: ['ai', 'rag', 'project-defense'],
    situation: 'A product or internal workflow needed LLM-assisted retrieval over domain data.',
    task: 'Build an integration that was useful, grounded and safe enough for real users.',
    action: [
      'Designed retrieval boundaries and context construction.',
      'Integrated model/tool calls with backend services.',
      'Handled evaluation, failure modes and observability.',
    ],
    result: 'The project showed ability to apply AI tooling pragmatically inside backend architecture.',
    adaptByCompany: 'For Abacum, connect to AI-native finance workflows and emphasize permission-aware retrieval and deterministic calculations.',
  },
  {
    id: 'performance-improvement',
    question: 'Tell me about a time you improved performance.',
    themes: ['performance', 'measurement'],
    situation: 'An endpoint, job or pipeline was slower than the product needed.',
    task: 'Improve it without guessing.',
    action: [
      'Established baseline metrics.',
      'Identified bottleneck through profiling, query plans or tracing.',
      'Applied targeted fixes such as batching, indexes, query rewrite, caching or async jobs.',
    ],
    result: 'Latency, throughput or cost improved with evidence.',
    adaptByCompany: 'Prepare a PostgreSQL or event-processing example; Abacum will care about reporting and calculation performance.',
  },
  {
    id: 'ownership',
    question: 'Tell me about ownership.',
    themes: ['ownership', 'seniority'],
    situation: 'A problem crossed code, operations, product and team boundaries.',
    task: 'Take responsibility for the outcome rather than only your assigned task.',
    action: [
      'Clarified the goal and stakeholders.',
      'Drove implementation, communication and follow-up.',
      'Made trade-offs visible and documented decisions.',
    ],
    result: 'The team had a better outcome and less ambiguity.',
    adaptByCompany: 'For Abacum, talk about owning a feature or platform improvement from product need to reliable operation.',
  },
  {
    id: 'speed-quality',
    question: 'Tell me about balancing speed and quality.',
    themes: ['delivery', 'quality'],
    situation: 'The team needed to ship quickly but there were real risks.',
    task: 'Choose a responsible scope and quality bar.',
    action: [
      'Separated core correctness from nice-to-have polish.',
      'Used feature flags or staged rollout.',
      'Added tests/monitoring around the highest-risk paths.',
    ],
    result: 'The team delivered quickly without creating avoidable product risk.',
    adaptByCompany: 'For Abacum, say financial correctness, permissions and auditability are quality bars that cannot be skipped.',
  },
]
