import type { DeepDiveTopic } from '../../types/content'

const django = (topic: Omit<DeepDiveTopic, 'group'>): DeepDiveTopic => ({ ...topic, group: 'Django' })
const fastapi = (topic: Omit<DeepDiveTopic, 'group'>): DeepDiveTopic => ({ ...topic, group: 'FastAPI' })
const sql = (topic: Omit<DeepDiveTopic, 'group'>): DeepDiveTopic => ({ ...topic, group: 'SQL' })

export const djangoTopics: DeepDiveTopic[] = [
  django({
    id: 'django-request-lifecycle',
    title: 'Request lifecycle',
    explanation: 'A Django request flows through the URL resolver, middleware chain, view, ORM/services, template or serializer layer, response middleware and exception handling.',
    interviewAnswer: 'I describe Django as a mature request/response framework: middleware wraps the request, URL routing selects a view, the view coordinates validation and business logic, and the ORM handles data access inside explicit transaction boundaries when needed.',
    miniExample: `A request to /reports/42 first passes authentication middleware, resolves to report_detail, checks permissions, fetches the report with select_related, serializes it and returns JSON.`,
    redFlags: ['Putting all business logic in views.', 'Not understanding middleware order.', 'Hiding database writes in signals.'],
    relevance: 'Finance SaaS endpoints need consistent permission checks, predictable transactions and auditable behavior across the lifecycle.',
    tags: ['django', 'architecture'],
  }),
  django({
    id: 'django-project-app-structure',
    title: 'Project and app structure',
    explanation: 'A Django project owns settings, URL roots and deployment wiring. Apps group domain functionality such as billing, integrations or reporting.',
    interviewAnswer: 'I keep apps cohesive around product domains, avoid giant shared apps, and place business workflows in services or use-case modules when model methods or views would become too broad.',
    miniExample: `apps/reports contains models.py, services/recalculate.py, selectors.py, tests/ and api.py; apps/integrations owns external sync logic.`,
    redFlags: ['One app named core containing everything.', 'Circular imports between apps.', 'Duplicated settings per environment with drift.'],
    relevance: 'Abacum-like products grow quickly; app boundaries should make ownership and refactoring easier.',
    tags: ['django', 'structure'],
  }),
  django({
    id: 'django-models-migrations',
    title: 'Models and migrations',
    explanation: 'Models define schema and domain constraints. Migrations version database changes and should be reviewed like production code.',
    interviewAnswer: 'I use model constraints and indexes for invariants the database must enforce, keep migrations reversible when practical, and plan risky changes with expand-and-contract deployments.',
    miniExample: `UniqueConstraint(fields=["tenant_id", "external_id", "source"], name="uniq_external_record_per_source") prevents duplicate integration imports.`,
    redFlags: ['Relying only on application validation for uniqueness.', 'Editing old migrations after they shipped.', 'Running large blocking migrations casually.'],
    relevance: 'Financial data needs durable constraints, safe schema evolution and deduplication guarantees.',
    tags: ['django', 'migrations', 'constraints'],
  }),
  django({
    id: 'django-orm-basics',
    title: 'ORM basics',
    explanation: 'Django QuerySets are lazy, composable database queries. Evaluation happens when iterated, sliced, counted or converted.',
    interviewAnswer: 'I use QuerySets to express filtering, joining, aggregation and ordering while being conscious of when queries execute and how many queries a code path creates.',
    miniExample: `Report.objects.filter(tenant=tenant, status="ready").order_by("-updated_at")[:20]`,
    redFlags: ['Assuming QuerySets execute immediately.', 'Looping and querying inside each iteration.', 'Using Python filtering instead of database filtering for large data.'],
    relevance: 'Good ORM habits are central to backend product performance in Django.',
    tags: ['django', 'orm'],
  }),
  django({
    id: 'django-select-prefetch',
    title: 'select_related vs prefetch_related',
    explanation: 'select_related uses SQL joins for single-valued relationships. prefetch_related uses separate queries and joins in Python for many-valued relationships.',
    interviewAnswer: 'For ForeignKey or OneToOne I reach for select_related; for reverse FK or ManyToMany I use prefetch_related, often with Prefetch when I need filtered related objects.',
    miniExample: `Report.objects.select_related("owner").prefetch_related("line_items")`,
    redFlags: ['Using prefetch_related for everything.', 'Not measuring query count.', 'Prefetching huge collections without filters.'],
    relevance: 'Reporting screens can easily create N+1 queries across tenants, departments and line items.',
    tags: ['django', 'performance', 'orm'],
  }),
  django({
    id: 'django-annotate-aggregate',
    title: 'annotate and aggregate',
    explanation: 'aggregate returns summary values for a whole QuerySet. annotate adds computed values per row or group.',
    interviewAnswer: 'I use aggregate for global totals and annotate for grouped or per-object values, while checking generated SQL when joins can multiply rows.',
    miniExample: `Department.objects.annotate(total_spend=Sum("expenses__amount")).order_by("-total_spend")`,
    redFlags: ['Confusing annotate and aggregate.', 'Not handling null totals.', 'Joining multiple many relationships and double-counting.'],
    relevance: 'FP&A products depend on correct grouped calculations and transparent totals.',
    tags: ['django', 'aggregation', 'finance'],
  }),
  django({
    id: 'django-f-q-expressions',
    title: 'F expressions and Q objects',
    explanation: 'F expressions perform database-side field operations. Q objects compose dynamic OR/AND/NOT filters.',
    interviewAnswer: 'I use F expressions to avoid race-prone read-modify-write updates and Q objects to keep complex filtering explicit and testable.',
    miniExample: `Budget.objects.filter(Q(status="open") | Q(owner=user)).update(version=F("version") + 1)`,
    redFlags: ['Updating counters in Python under concurrency.', 'Building unsafe dynamic filters.', 'Forgetting operator precedence with Q objects.'],
    relevance: 'Budget versions, counters and flexible report filters often need these tools.',
    tags: ['django', 'orm', 'concurrency'],
  }),
  django({
    id: 'django-transactions',
    title: 'Transactions and transaction.atomic',
    explanation: 'transaction.atomic groups database operations so they commit together or roll back together. It can be nested with savepoints.',
    interviewAnswer: 'I wrap multi-step writes that must stay consistent in transaction.atomic, keep the block small, and avoid doing external network calls inside the transaction.',
    miniExample: `with transaction.atomic(): create_import_batch(); upsert_rows(); mark_batch_completed()`,
    redFlags: ['Long transactions around API calls.', 'Assuming atomic protects external systems.', 'Missing idempotency on retries.'],
    relevance: 'Financial imports and recalculations must avoid partial writes and inconsistent states.',
    tags: ['django', 'transactions'],
  }),
  django({
    id: 'django-service-layer',
    title: 'Service layer vs fat models vs fat views',
    explanation: 'Views should coordinate HTTP concerns, models should hold local invariants, and services/use cases can orchestrate workflows across models and integrations.',
    interviewAnswer: 'I avoid dogma: simple domain behavior can live on models, but multi-step workflows such as importing financial data or recalculating forecasts belong in explicit services with focused tests.',
    miniExample: `recalculate_forecast(plan_id) loads inputs, validates permissions, runs formulas, persists results and emits events.`,
    redFlags: ['Everything in views.', 'An anemic codebase with no clear owner for business rules.', 'Services that become unstructured dumping grounds.'],
    relevance: 'Complex SaaS business logic needs discoverable ownership and testable orchestration.',
    tags: ['django', 'architecture'],
  }),
  django({
    id: 'django-pytest',
    title: 'Testing with pytest',
    explanation: 'pytest with pytest-django gives concise fixtures, database access markers and expressive assertions for Django code.',
    interviewAnswer: 'I test business services at the unit/integration boundary, use factories for data setup, and add query-count or transaction tests for performance-sensitive code.',
    miniExample: `@pytest.mark.django_db
def test_recalculate_forecast(factory):
    plan = factory.plan()
    assert recalculate_forecast(plan.id).status == "ready"`,
    redFlags: ['Only testing views through snapshots.', 'Slow fixture setup everywhere.', 'No tests for edge cases and permissions.'],
    relevance: 'A finance product needs trust in calculations, permissions and import behavior.',
    tags: ['django', 'testing'],
  }),
  django({
    id: 'django-factories',
    title: 'Factories',
    explanation: 'Factories create test data with sensible defaults while allowing each test to override only what matters.',
    interviewAnswer: 'I prefer factories over huge fixtures because they keep tests local, readable and resilient to model changes.',
    miniExample: `invoice = InvoiceFactory(tenant=tenant, amount=Decimal("100.00"))`,
    redFlags: ['Global fixtures that hide test meaning.', 'Factories with random defaults that make tests flaky.', 'Creating full object graphs unnecessarily.'],
    relevance: 'Factories make it practical to test many finance edge cases without unreadable setup.',
    tags: ['django', 'testing'],
  }),
  django({
    id: 'django-n-plus-one',
    title: 'Avoiding N+1 queries',
    explanation: 'N+1 happens when code runs one query for a list and then one additional query per item for related data.',
    interviewAnswer: 'I detect N+1 with debug toolbar, logs or query-count tests, then fix it with select_related, prefetch_related, annotations or a purpose-built read query.',
    miniExample: `with django_assert_num_queries(2): list_reports_for_dashboard(tenant)`,
    redFlags: ['Fixing performance only with caching.', 'Prefetching excessive data.', 'Not checking serializers for hidden related access.'],
    relevance: 'Dashboards and report lists are prime N+1 territory.',
    tags: ['django', 'performance'],
  }),
  django({
    id: 'django-query-optimization',
    title: 'Query optimization',
    explanation: 'Optimization combines good filtering, indexing, joins, annotations, pagination and reading the generated SQL.',
    interviewAnswer: 'I start by measuring the slow path, inspect SQL and query plans, then choose the smallest fix: index, query rewrite, prefetch, denormalized read model or cache.',
    miniExample: `queryset.explain(analyze=True) in a safe environment can show whether an index is used.`,
    redFlags: ['Adding indexes blindly.', 'Caching incorrect or tenant-sensitive data.', 'Optimizing without a baseline.'],
    relevance: 'Financial reporting must feel fast while preserving correctness and tenant isolation.',
    tags: ['django', 'sql', 'performance'],
  }),
  django({
    id: 'django-indexes-constraints',
    title: 'Indexes and constraints',
    explanation: 'Indexes speed reads and constraints enforce invariants. Both are part of application design, not only DBA work.',
    interviewAnswer: 'I add indexes based on actual filters, joins and ordering, and I use constraints for tenant-scoped uniqueness, valid states and non-negative amounts when appropriate.',
    miniExample: `models.Index(fields=["tenant", "period", "department"])`,
    redFlags: ['Indexing every column.', 'No unique constraints for external IDs.', 'Forgetting migration impact on large tables.'],
    relevance: 'Integration deduplication and reporting queries are database-level design problems.',
    tags: ['django', 'postgresql'],
  }),
  django({
    id: 'django-permissions-multitenancy',
    title: 'Permissions and multi-tenancy',
    explanation: 'Multi-tenant apps must consistently scope data by tenant and enforce role/resource permissions before returning or mutating data.',
    interviewAnswer: 'I design tenant scoping as a default query concern, combine RBAC with object-level checks where needed, and test cross-tenant denial paths explicitly.',
    miniExample: `Report.objects.filter(tenant=request.user.tenant, id=report_id).get()`,
    redFlags: ['Fetching by id before tenant filtering.', 'Only hiding UI actions.', 'No audit trail for permission-sensitive operations.'],
    relevance: 'Finance data is sensitive; one cross-tenant leak is catastrophic.',
    tags: ['django', 'security', 'saas'],
  }),
  django({
    id: 'django-background-jobs',
    title: 'Background jobs',
    explanation: 'Jobs handle slow or retryable work such as imports, recalculations, emails and data synchronization.',
    interviewAnswer: 'I keep HTTP requests fast, enqueue idempotent jobs after commit, store job state, retry transient failures and make the operation observable.',
    miniExample: `transaction.on_commit(lambda: recalculate_plan.delay(plan_id))`,
    redFlags: ['Enqueueing before the database commit.', 'Non-idempotent retries.', 'No dead-letter or failure visibility.'],
    relevance: 'Forecast recalculation and external integrations naturally belong in background processing.',
    tags: ['django', 'jobs', 'reliability'],
  }),
  django({
    id: 'django-admin',
    title: 'Admin usage',
    explanation: 'Django admin is useful for internal operations, debugging and controlled back-office workflows, but should not become the product itself by accident.',
    interviewAnswer: 'I use admin for safe internal workflows with permissions, search, list filters and read-only fields for sensitive data.',
    miniExample: `readonly_fields = ["created_at", "updated_at", "external_id"]`,
    redFlags: ['Giving broad admin access.', 'Editing production financial data without audit.', 'Putting customer-facing workflows only in admin.'],
    relevance: 'Admin can help operations inspect imports, jobs and customer issues safely.',
    tags: ['django', 'operations'],
  }),
  django({
    id: 'django-signals',
    title: 'Signals and why to be careful',
    explanation: 'Signals decouple event-like reactions from model operations, but they can hide side effects and make flow hard to reason about.',
    interviewAnswer: 'I use signals sparingly for cross-cutting reactions and prefer explicit service orchestration for important business workflows.',
    miniExample: `A post_save signal for cache invalidation may be fine; a signal that recalculates financial statements is usually too hidden.`,
    redFlags: ['Critical writes hidden in post_save.', 'Signals firing in tests unexpectedly.', 'Recursive signal behavior.'],
    relevance: 'Financial workflows need explicit, auditable control flow.',
    tags: ['django', 'architecture'],
  }),
  django({
    id: 'django-middleware',
    title: 'Middleware',
    explanation: 'Middleware wraps request and response processing for cross-cutting concerns such as authentication, correlation IDs, security headers and logging.',
    interviewAnswer: 'I use middleware for concerns that truly apply across many endpoints, while keeping domain-specific decisions in views/services.',
    miniExample: `A request_id middleware adds a correlation id to logs and response headers.`,
    redFlags: ['Database-heavy middleware on every request.', 'Domain permissions hidden globally.', 'Order-dependent behavior that is not documented.'],
    relevance: 'Observability, auth context and tenant context often start at middleware boundaries.',
    tags: ['django', 'middleware'],
  }),
]

export const fastApiTopics: DeepDiveTopic[] = [
  fastapi({
    id: 'fastapi-request-handling',
    title: 'Request handling compared with Django',
    explanation: 'FastAPI routes are function-first and type-hint driven; Django views are framework-first and often class/function views around a mature batteries-included stack.',
    interviewAnswer: 'I can transfer the same principles: thin HTTP boundary, explicit validation, clear service layer, predictable data access and focused tests. The syntax changes, the backend judgment does not.',
    miniExample: `FastAPI route dependency injection maps well to explicit Django view/service parameters.`,
    redFlags: ['Presenting FastAPI and Django as unrelated worlds.', 'Ignoring Django middleware and ORM conventions.', 'Overusing async when not needed.'],
    relevance: "This is Guillermo's bridge: sound FastAPI backend habits can become Django productivity quickly.",
    tags: ['fastapi', 'django', 'transferable'],
  }),
  fastapi({
    id: 'fastapi-dependency-injection',
    title: 'Dependency injection',
    explanation: 'FastAPI uses Depends to declare dependencies for auth, database sessions, settings and shared request logic.',
    interviewAnswer: 'In Django I would translate this to middleware, decorators, service parameters, custom managers or explicit dependency wiring rather than hiding everything globally.',
    miniExample: `get_current_user in FastAPI becomes request.user plus explicit permission checks in Django.`,
    redFlags: ['Assuming Django has the same DI mechanism.', 'Putting business state in globals.', 'Hard-to-test hidden dependencies.'],
    relevance: 'Explaining this shows transferable architecture maturity.',
    tags: ['fastapi', 'django', 'architecture'],
  }),
  fastapi({
    id: 'fastapi-validation-pydantic',
    title: 'Validation and Pydantic',
    explanation: 'FastAPI leans on Pydantic models for request parsing, validation and serialization.',
    interviewAnswer: 'The Django equivalent may be forms, DRF serializers, Pydantic in services, or explicit validation. I focus on clear input contracts and validation close to boundaries.',
    miniExample: `A ForecastInput Pydantic model becomes a DRF serializer or service DTO validating period, scenario and line items.`,
    redFlags: ['Mixing validation into persistence models blindly.', 'No boundary validation.', 'Trusting external integration payloads.'],
    relevance: 'Data quality is essential for imported financial records.',
    tags: ['fastapi', 'validation'],
  }),
  fastapi({
    id: 'fastapi-async',
    title: 'Async',
    explanation: 'FastAPI has first-class async support. Django supports async views too, but many Django stacks remain sync around ORM and middleware constraints.',
    interviewAnswer: 'I choose async for I/O-heavy concurrency when the stack supports it end to end. For Django product work, background jobs and efficient queries often matter more than async views.',
    miniExample: `External API fan-out can be async, while financial recalculation may be a background job with transactional writes.`,
    redFlags: ['Using async as a performance magic wand.', 'Blocking inside async functions.', 'Ignoring database connection behavior.'],
    relevance: 'Abacum-like integrations may need concurrency, but correctness and retries are the bigger design concerns.',
    tags: ['fastapi', 'async'],
  }),
  fastapi({
    id: 'fastapi-openapi',
    title: 'OpenAPI',
    explanation: 'FastAPI generates OpenAPI from route signatures and Pydantic models, making contracts visible by default.',
    interviewAnswer: 'In Django I would expect DRF schema tooling or explicit API documentation. The important habit is maintaining accurate contracts for frontend and integration consumers.',
    miniExample: `Typed request/response schemas prevent drift between backend and frontend finance workflows.`,
    redFlags: ['Docs that do not match behavior.', 'No examples for error responses.', 'Breaking clients without versioning.'],
    relevance: 'Reporting and integration APIs benefit from stable, documented contracts.',
    tags: ['fastapi', 'api-design'],
  }),
  fastapi({
    id: 'fastapi-app-structure',
    title: 'App structure',
    explanation: 'FastAPI projects often use routers, schemas, services and repositories. Django uses apps, models, views, serializers/forms and services/selectors.',
    interviewAnswer: 'I structure by domain rather than by technical layer alone, and I make business workflows testable outside HTTP handlers.',
    miniExample: `forecasting/router.py in FastAPI maps to apps/forecasting/api.py plus services in Django.`,
    redFlags: ['Route files containing all logic.', 'Repository abstractions that duplicate the ORM without value.', 'No domain ownership.'],
    relevance: 'Shows Guillermo can bring clean architecture habits without fighting Django conventions.',
    tags: ['fastapi', 'structure'],
  }),
  fastapi({
    id: 'fastapi-business-logic',
    title: 'Where business logic lives',
    explanation: 'Business logic should be independent enough to test without HTTP and concrete enough to reflect product rules.',
    interviewAnswer: 'Whether in FastAPI or Django, I keep handlers thin and put workflows in services/use cases, with model methods for local invariants.',
    miniExample: `calculate_variance(report_id) should be callable from API, job and tests.`,
    redFlags: ['Logic duplicated between API and jobs.', 'Hard-coded product rules in serializers.', 'No pure functions for calculation-heavy code.'],
    relevance: 'Financial calculations need deterministic, reusable, well-tested rules.',
    tags: ['fastapi', 'django', 'domain'],
  }),
  fastapi({
    id: 'fastapi-testing-transfer',
    title: 'Testing transferability',
    explanation: 'FastAPI tests often use dependency overrides and TestClient; Django tests use client fixtures, factories and database markers.',
    interviewAnswer: 'The testing shape transfers: isolate business rules, integration-test persistence and permissions, use factories, and keep HTTP tests focused on contracts.',
    miniExample: `A FastAPI dependency override for a fake service becomes a Django monkeypatch or injected service parameter in tests.`,
    redFlags: ['Only testing happy-path endpoints.', 'No database transaction tests.', 'Flaky tests because time/external APIs are not controlled.'],
    relevance: 'Testing credibility offsets the Django refresh risk.',
    tags: ['fastapi', 'testing'],
  }),
]

export const sqlTopics: DeepDiveTopic[] = [
  sql({
    id: 'sql-group-by',
    title: 'GROUP BY',
    explanation: 'GROUP BY collapses rows into groups and lets aggregate functions compute totals, counts, averages and other summaries.',
    interviewAnswer: 'I group on the business dimensions needed by the report, aggregate numeric measures, and watch for joins that multiply rows before aggregation.',
    miniExample: `SELECT department_id, date_trunc('month', booked_at) AS month, SUM(amount)
FROM expenses
GROUP BY department_id, month;`,
    redFlags: ['Selecting non-grouped columns casually.', 'Aggregating after a row-multiplying join.', 'Ignoring null handling.'],
    relevance: 'FP&A dashboards are built on grouped actuals, forecasts and variance calculations.',
    tags: ['sql', 'finance'],
  }),
  sql({
    id: 'sql-joins',
    title: 'Joins',
    explanation: 'Joins combine rows from related tables. Inner joins require matches; left joins preserve the left side with nulls for missing matches.',
    interviewAnswer: 'I choose join type based on business semantics: for example, keep departments with no expenses using left join, but use inner join when a child row must exist.',
    miniExample: `SELECT d.name, COALESCE(SUM(e.amount), 0)
FROM departments d
LEFT JOIN expenses e ON e.department_id = d.id
GROUP BY d.name;`,
    redFlags: ['Using inner joins that drop empty groups.', 'Joining on non-indexed or wrong keys.', 'Not understanding cardinality.'],
    relevance: 'Reports often need complete dimensions, even when some values are zero.',
    tags: ['sql', 'joins'],
  }),
  sql({
    id: 'sql-indexes',
    title: 'Indexes',
    explanation: 'Indexes trade write/storage cost for faster lookups, joins and ordering. PostgreSQL B-tree indexes are the default for equality and range queries.',
    interviewAnswer: 'I add indexes for measured query patterns: tenant filters, foreign keys, date ranges and ordering. Then I verify with EXPLAIN ANALYZE.',
    miniExample: `CREATE INDEX CONCURRENTLY idx_expenses_tenant_period ON expenses (tenant_id, period);`,
    redFlags: ['Indexing every column.', 'Ignoring write overhead.', 'Not using concurrent index creation on large production tables.'],
    relevance: 'Tenant-scoped reporting queries need predictable index paths.',
    tags: ['sql', 'performance'],
  }),
  sql({
    id: 'sql-composite-indexes',
    title: 'Composite indexes',
    explanation: 'Composite indexes cover multiple columns. Order matters: leftmost columns are most useful for filtering and sorting.',
    interviewAnswer: 'I design composite indexes around common WHERE plus ORDER BY patterns, usually tenant_id first in multi-tenant SaaS, followed by selective filters or time.',
    miniExample: `CREATE INDEX idx_records_tenant_source_external ON records (tenant_id, source, external_id);`,
    redFlags: ['Wrong column order.', 'Duplicate overlapping indexes.', 'Expecting a composite index to help arbitrary suffix-only filters.'],
    relevance: 'Deduplication and tenant isolation often rely on tenant + source + external id patterns.',
    tags: ['sql', 'indexes', 'saas'],
  }),
  sql({
    id: 'sql-explain-analyze',
    title: 'EXPLAIN ANALYZE',
    explanation: 'EXPLAIN shows the planned execution path; ANALYZE runs the query and reports actual timing and row counts.',
    interviewAnswer: 'I compare estimated vs actual rows, identify scans, joins, sorts and buffers, then make targeted changes to query shape, indexes or statistics.',
    miniExample: `EXPLAIN (ANALYZE, BUFFERS) SELECT * FROM expenses WHERE tenant_id = 42 AND period = '2026-01';`,
    redFlags: ['Only reading the top cost number.', 'Running ANALYZE on dangerous writes without care.', 'Not checking row-estimate mismatch.'],
    relevance: 'This is the practical tool for fixing slow reporting queries.',
    tags: ['sql', 'performance'],
  }),
  sql({
    id: 'sql-transactions',
    title: 'Transactions',
    explanation: 'Transactions group statements so they commit or roll back as one unit, preserving database consistency.',
    interviewAnswer: 'For financial workflows I use transactions for multi-table writes, keep them short, and combine them with idempotency and constraints.',
    miniExample: `BEGIN;
INSERT INTO import_batches (...);
INSERT INTO financial_records (...);
COMMIT;`,
    redFlags: ['Long transactions around network calls.', 'No retry strategy for serialization failures.', 'Assuming transactions cover external APIs.'],
    relevance: 'Imports, recalculations and audit writes must not partially apply.',
    tags: ['sql', 'transactions'],
  }),
  sql({
    id: 'sql-isolation-levels',
    title: 'Isolation levels',
    explanation: 'Isolation levels control what concurrent transactions can see. PostgreSQL defaults to read committed, with repeatable read and serializable for stronger guarantees.',
    interviewAnswer: 'I start with read committed plus explicit locks/constraints, and move to stronger isolation only when the business invariant needs it and I can handle retries.',
    miniExample: `Serializable can prevent write skew but requires retrying serialization failures.`,
    redFlags: ['Not knowing the default.', 'Assuming repeatable read prevents every anomaly.', 'Ignoring retry behavior.'],
    relevance: 'Concurrent edits to budgets or forecasts can create subtle correctness bugs.',
    tags: ['sql', 'concurrency'],
  }),
  sql({
    id: 'sql-row-locking',
    title: 'Row-level locking',
    explanation: 'SELECT FOR UPDATE locks selected rows until transaction commit, preventing concurrent updates from racing.',
    interviewAnswer: 'I use row locks for small, well-scoped critical sections such as updating a budget version or claiming a job, and avoid locking broad report queries.',
    miniExample: `SELECT * FROM budgets WHERE id = 10 FOR UPDATE;`,
    redFlags: ['Locking too many rows.', 'Deadlocks from inconsistent lock order.', 'Holding locks while calling external services.'],
    relevance: 'Finance workflows often need safe sequential updates to sensitive records.',
    tags: ['sql', 'locking'],
  }),
  sql({
    id: 'sql-optimistic-concurrency',
    title: 'Optimistic concurrency',
    explanation: 'Optimistic concurrency uses version numbers or timestamps to detect conflicting writes without locking in advance.',
    interviewAnswer: 'I update with a WHERE id = ? AND version = ? condition and fail gracefully if no rows are updated, asking the user or job to reload.',
    miniExample: `UPDATE budgets SET amount = 1200, version = version + 1 WHERE id = 10 AND version = 3;`,
    redFlags: ['Last-write-wins on critical finance data.', 'No user-facing conflict handling.', 'Using timestamps with weak precision.'],
    relevance: 'Collaborative planning needs conflict detection without excessive locking.',
    tags: ['sql', 'concurrency'],
  }),
  sql({
    id: 'sql-pagination',
    title: 'Pagination',
    explanation: 'Offset pagination is simple but slow for deep pages. Keyset pagination uses a stable cursor based on ordered columns.',
    interviewAnswer: 'I use offset for small admin-like lists and keyset pagination for high-volume timelines or reports, always with deterministic ordering.',
    miniExample: `WHERE (created_at, id) < (:cursor_created_at, :cursor_id)
ORDER BY created_at DESC, id DESC
LIMIT 50;`,
    redFlags: ['ORDER BY missing.', 'Deep OFFSET scans on large tables.', 'Cursor fields not indexed.'],
    relevance: 'Large audit logs and record lists need stable, fast pagination.',
    tags: ['sql', 'api', 'performance'],
  }),
  sql({
    id: 'sql-avoiding-slow-queries',
    title: 'Avoiding slow queries',
    explanation: 'Slow query prevention is a mix of schema design, indexes, bounded result sets, query plans, caching and product constraints.',
    interviewAnswer: 'I set performance budgets, add observability, inspect plans, limit unbounded filters and move repeated expensive calculations into read models or materialized views when justified.',
    miniExample: `A report endpoint should require tenant and period filters rather than allowing unbounded all-time scans by default.`,
    redFlags: ['Unbounded exports through synchronous APIs.', 'No query timeout.', 'Caching tenant-sensitive data without keys.'],
    relevance: 'Reporting products become slow if query boundaries are not designed into the product.',
    tags: ['sql', 'performance'],
  }),
  sql({
    id: 'sql-orm-n-plus-one',
    title: 'N+1 from ORM',
    explanation: 'ORM code can accidentally execute one query per object when traversing relationships lazily.',
    interviewAnswer: 'I identify N+1 with query logs or tests and solve it with joins, prefetches, annotations or explicit SQL/read models depending on cardinality.',
    miniExample: `Looping reports and accessing report.owner.name can become N+1 unless owner is select_related.`,
    redFlags: ['Blaming the ORM instead of measuring.', 'Prefetching huge related sets.', 'Serializers hiding queries.'],
    relevance: 'Dashboard endpoints often combine many related entities.',
    tags: ['sql', 'django', 'performance'],
  }),
  sql({
    id: 'sql-audit-tables',
    title: 'Audit tables',
    explanation: 'Audit tables record who changed what, when and why, often with before/after values or immutable domain events.',
    interviewAnswer: 'For finance data I design append-only audit events with actor, tenant, entity, timestamp, reason/correlation id and enough diff data to investigate changes.',
    miniExample: `budget_audit(id, tenant_id, budget_id, actor_id, action, before_json, after_json, created_at)`,
    redFlags: ['Overwriting history.', 'No actor or correlation id.', 'Audit writes outside the main transaction.'],
    relevance: 'Trust and compliance depend on traceability of financial changes.',
    tags: ['sql', 'audit', 'finance'],
  }),
  sql({
    id: 'sql-financial-calculation-storage',
    title: 'Financial calculation storage',
    explanation: 'Calculation results can be computed on read, stored as snapshots, or represented as immutable events plus materialized projections.',
    interviewAnswer: 'I choose based on freshness, explainability and cost. For expensive or audited calculations, I store versioned snapshots with input references and recalculation metadata.',
    miniExample: `forecast_results(plan_id, version, line_item_id, amount, inputs_hash, calculated_at)`,
    redFlags: ['No way to reproduce a number.', 'Mixing draft and approved values.', 'Recalculating expensive reports synchronously for every request.'],
    relevance: 'FP&A users need fast numbers they can trust and explain.',
    tags: ['sql', 'finance', 'architecture'],
  }),
  sql({
    id: 'sql-materialized-views',
    title: 'Materialized views',
    explanation: 'Materialized views store query results and can be refreshed to speed repeated expensive reads.',
    interviewAnswer: 'I use materialized views for stable, expensive aggregations when freshness requirements allow it, and I design refresh strategy and invalidation carefully.',
    miniExample: `CREATE MATERIALIZED VIEW monthly_spend AS SELECT tenant_id, period, SUM(amount) FROM expenses GROUP BY tenant_id, period;`,
    redFlags: ['No refresh plan.', 'Serving stale data without communicating freshness.', 'Using materialized views where a normal index would solve it.'],
    relevance: 'Financial dashboards often need repeated aggregations over large datasets.',
    tags: ['sql', 'performance', 'reporting'],
  }),
  sql({
    id: 'sql-jsonb-tradeoffs',
    title: 'JSONB trade-offs',
    explanation: 'JSONB is flexible and indexable, but it weakens relational constraints and can hide important schema evolution.',
    interviewAnswer: 'I use JSONB for external payloads, sparse metadata or evolving fields, but promote stable business fields to columns when they need constraints, joins or frequent filtering.',
    miniExample: `Store raw integration payload in jsonb, but extract tenant_id, source, external_id, period and amount into typed columns.`,
    redFlags: ['Everything in JSONB.', 'No validation of JSON shape.', 'Slow filters on unindexed JSON paths.'],
    relevance: 'External financial integrations need both raw payload retention and reliable queryable fields.',
    tags: ['sql', 'jsonb', 'integrations'],
  }),
]

export const deepDiveTopics = [...djangoTopics, ...fastApiTopics, ...sqlTopics]
