import type { Flashcard } from '../../types/content'

type CardSeed = [question: string, answer: string, tags?: string[]]

function cards(group: string, seeds: CardSeed[]): Flashcard[] {
  return seeds.map(([question, answer, tags = []], index) => ({
    id: `${group.toLowerCase().replaceAll(' ', '-')}-${index + 1}`,
    group,
    question,
    answer,
    tags: [group.toLowerCase(), ...tags],
  }))
}

export const flashcards: Flashcard[] = [
  ...cards('Python', [
    ['When is defaultdict useful?', 'When missing keys should automatically create a default value, such as grouping totals by department or month.', ['dict']],
    ['Why avoid a mutable default argument?', 'The same object is reused across calls, so state can leak between invocations.', ['pitfall']],
    ['What is the difference between list comprehension and generator expression?', 'A list comprehension materializes immediately; a generator yields lazily and can reduce memory use.', ['iterators']],
    ['How do you sort by two criteria?', 'Use key with a tuple, for example key=lambda item: (-item.total, item.name).', ['sorting']],
    ['What should you clarify before coding a finance aggregation?', 'Input shape, invalid rows, money precision, duplicate records, rounding rules and expected output order.', ['interview']],
    ['What is idempotency?', 'The same operation can be safely repeated without changing the final result beyond the first successful application.', ['backend']],
    ['Why use Decimal for money?', 'Decimal avoids binary floating point surprises and supports explicit rounding policies.', ['finance']],
    ['What does enumerate give you?', 'Pairs of index and value, useful for row-level validation errors.', ['basics']],
    ['How do you detect duplicates in O(n)?', 'Build a set of unique keys and report records whose key has already been seen.', ['sets']],
    ['What is a stable tie-breaker?', 'An additional deterministic sort criterion so equal primary values always appear in predictable order.', ['sorting']],
    ['When would you use heapq.nlargest?', 'When you need top N from a large collection and N is much smaller than the number of groups.', ['performance']],
    ['What is topological sort used for?', 'Ordering nodes so dependencies come before dependents, such as formula recalculation order.', ['graphs']],
    ['What makes a good live coding helper function?', 'Small scope, clear name, easy tests and no hidden external state.', ['interview']],
    ['How do you communicate complexity?', 'State time and space in terms of input sizes after explaining the main data structures.', ['interview']],
    ['How should missing values be handled?', 'Clarify requirements; common choices are reject, skip, default or collect validation errors.', ['validation']],
  ]),
  ...cards('Django', [
    ['What is a QuerySet?', 'A lazy, composable representation of a database query that executes when evaluated.', ['orm']],
    ['select_related or prefetch_related for ForeignKey?', 'select_related, because it uses a SQL join for single-valued relationships.', ['orm']],
    ['select_related or prefetch_related for ManyToMany?', 'prefetch_related, because it uses separate queries and joins objects in Python.', ['orm']],
    ['What does transaction.atomic do?', 'It groups database operations so they commit together or roll back together.', ['transactions']],
    ['Why use F expressions?', 'To perform database-side updates and avoid race-prone read-modify-write patterns.', ['orm']],
    ['Why use Q objects?', 'To compose complex OR, AND and NOT filters explicitly.', ['orm']],
    ['What is an N+1 query?', 'One query loads a list, then one additional query is executed per item for related data.', ['performance']],
    ['Where should business logic live?', 'Simple invariants can live on models; multi-step workflows are often clearer in services/use cases.', ['architecture']],
    ['Why be careful with signals?', 'They hide side effects and can make important business flows difficult to trace and test.', ['architecture']],
    ['How do migrations affect production?', 'They change real schema and can lock or rewrite large tables, so risky migrations need planning.', ['migrations']],
    ['What should factories do in tests?', 'Create readable test data with sensible defaults and explicit overrides.', ['testing']],
    ['How do you avoid cross-tenant leaks?', 'Always scope queries by tenant before object lookup and test denial paths.', ['security']],
    ['What is annotate used for?', 'Adding computed values per object or group in a QuerySet.', ['aggregation']],
    ['What is aggregate used for?', 'Returning summary values for the whole QuerySet.', ['aggregation']],
    ['When enqueue a background job after a DB write?', 'After commit, so the worker cannot observe data that later rolls back.', ['jobs']],
  ]),
  ...cards('FastAPI', [
    ['What is Depends used for?', 'Declaring reusable request dependencies such as auth, DB sessions or settings.', ['di']],
    ['What does Pydantic provide?', 'Typed parsing, validation and serialization of request and response models.', ['validation']],
    ['When is async useful in FastAPI?', 'For I/O-heavy concurrency when the full call path avoids blocking operations.', ['async']],
    ['What is automatic OpenAPI useful for?', 'It keeps API contracts discoverable and client-friendly when schemas are accurate.', ['api']],
    ['How do FastAPI skills transfer to Django?', 'Thin handlers, explicit validation, service-layer thinking, tests and database discipline transfer directly.', ['django']],
    ['What is dependency override in tests?', 'Replacing a real dependency with a fake/stub for focused test behavior.', ['testing']],
    ['Where should FastAPI business logic live?', 'Outside route handlers, typically in services/use cases or domain functions.', ['architecture']],
    ['What is a response model?', 'A declared schema that controls and documents what the API returns.', ['api']],
    ['Why avoid blocking work inside async endpoints?', 'It blocks the event loop and harms concurrency.', ['async']],
    ['How should external API calls be handled?', 'With timeouts, retries, circuit-breaker thinking, observability and fallback behavior.', ['reliability']],
    ['What is middleware used for?', 'Cross-cutting request/response concerns such as correlation IDs, CORS or timing.', ['architecture']],
    ['What is a router?', 'A grouping of related routes that keeps APIs modular.', ['structure']],
    ['How do you validate domain rules beyond schema?', 'Use service/domain validation and tests; schema validation only proves shape/type.', ['domain']],
    ['How do you explain FastAPI to a Django team?', 'As a typed API framework whose good practices map to Django through views, serializers, services and tests.', ['communication']],
    ['What is a common FastAPI overengineering trap?', 'Adding too many abstractions or async complexity before the product needs it.', ['judgment']],
  ]),
  ...cards('SQL', [
    ['What does GROUP BY do?', 'It groups rows by dimensions so aggregate functions can compute summaries.', ['aggregation']],
    ['When use LEFT JOIN?', 'When you need to keep left-side rows even if there is no matching right-side row.', ['joins']],
    ['Why does composite index order matter?', 'The leftmost columns determine which filters/orderings can efficiently use the index.', ['indexes']],
    ['What does EXPLAIN ANALYZE add over EXPLAIN?', 'It actually runs the query and shows real timing and row counts.', ['performance']],
    ['What is row-level locking?', 'Locking selected rows, often with SELECT FOR UPDATE, so concurrent transactions cannot update them simultaneously.', ['locking']],
    ['What is optimistic concurrency?', 'Detecting conflicts with a version/timestamp condition rather than locking first.', ['concurrency']],
    ['Why is OFFSET pagination slow for deep pages?', 'The database still has to scan/skip many rows before returning the page.', ['pagination']],
    ['What is keyset pagination?', 'Cursor-based pagination using stable ordered columns, such as created_at and id.', ['pagination']],
    ['What is a materialized view?', 'A stored result of a query that can be refreshed to speed repeated expensive reads.', ['reporting']],
    ['When use JSONB?', 'For flexible metadata or raw external payloads, while keeping stable queryable fields as typed columns.', ['jsonb']],
    ['What is an audit table?', 'A structured history of changes with actor, entity, timestamp and before/after or event details.', ['audit']],
    ['How do you prevent duplicate external records?', 'Use a unique constraint on tenant, source and external_id plus idempotent ingestion.', ['integrations']],
    ['What is transaction isolation?', 'Rules controlling what concurrent transactions can see and which anomalies can occur.', ['transactions']],
    ['Why can ORMs cause slow SQL?', 'Lazy relationship access and hidden queries can create N+1 patterns or inefficient joins.', ['orm']],
    ['What is the first step in query optimization?', 'Measure the slow query and read the plan before changing schema or code.', ['performance']],
  ]),
  ...cards('System Design', [
    ['What is the first move in system design?', 'Clarify requirements, constraints, scale and success metrics before drawing architecture.', ['interview']],
    ['Why start simple?', 'A simple correct baseline makes trade-offs visible and prevents premature distributed complexity.', ['judgment']],
    ['What is a read model?', 'A data representation optimized for reads, often denormalized or precomputed from source data.', ['architecture']],
    ['What is eventual consistency?', 'A model where replicas/projections may lag but converge if no new updates occur.', ['consistency']],
    ['What is the outbox pattern?', 'Writing events to a database table in the same transaction as business data, then publishing asynchronously.', ['events']],
    ['How do you design for retries?', 'Make operations idempotent, use dedupe keys and track attempt state.', ['reliability']],
    ['What belongs in observability?', 'Metrics, logs, traces, correlation IDs, alerts and business-level health indicators.', ['observability']],
    ['When use background jobs?', 'For slow, retryable or asynchronous work that should not block the request path.', ['jobs']],
    ['What is cache stampede?', 'Many requests recompute the same missing cache value at once after expiry or invalidation.', ['caching']],
    ['How do you protect multi-tenant data?', 'Tenant-scoped queries, object permissions, tests, audit logs and safe cache keys.', ['security']],
    ['What is a failure mode?', 'A way the system can break or degrade, such as stale data, duplicate messages or worker crashes.', ['reliability']],
    ['What is backpressure?', 'A mechanism to slow producers or shed load when consumers cannot keep up.', ['scaling']],
    ['How should a design answer end?', 'With the core trade-offs, why the design meets requirements and what you would monitor.', ['interview']],
    ['What is a versioned snapshot?', 'Stored computed state tied to a specific input version so results are reproducible.', ['finance']],
    ['When is Kafka not necessary?', 'When simple request/response or a basic task queue satisfies ordering, replay and scale requirements.', ['judgment']],
  ]),
  ...cards('AWS', [
    ['What is IAM least privilege?', 'Granting only the permissions a role needs, scoped as narrowly as practical.', ['security']],
    ['What is S3 good for?', 'Durable object storage for files, exports, logs and static assets.', ['storage']],
    ['What is CloudFront?', 'A CDN that caches and serves content closer to users.', ['cdn']],
    ['What does Lambda@Edge do?', 'Runs limited code at CloudFront edge locations for request/response customization.', ['edge']],
    ['What is ECS/EKS used for?', 'Running containerized services; ECS is AWS-managed orchestration, EKS is managed Kubernetes.', ['containers']],
    ['Why use RDS PostgreSQL?', 'Managed relational database operations such as backups, patching and replication.', ['database']],
    ['What is SQS useful for?', 'Reliable queueing for decoupled background processing.', ['queues']],
    ['What is SNS useful for?', 'Pub/sub fan-out notifications to multiple subscribers.', ['messaging']],
    ['What is CloudWatch?', 'AWS monitoring/logging/metrics service.', ['observability']],
    ['What is Bedrock?', 'AWS managed access to foundation models through a unified service interface.', ['ai']],
    ['How do you control AWS cost for LLM calls?', 'Model choice, token limits, caching, rate limits, budgets and monitoring.', ['cost']],
    ['What is a VPC?', 'A logically isolated network boundary for AWS resources.', ['network']],
    ['What should go in Secrets Manager?', 'Sensitive credentials such as API keys and database passwords.', ['security']],
    ['What is blue/green deployment?', 'Deploying a new environment alongside the old one and shifting traffic after validation.', ['deployment']],
    ['What is an AWS production readiness habit?', 'Timeouts, retries, alarms, IAM review, cost visibility and rollback planning.', ['reliability']],
  ]),
  ...cards('Kafka', [
    ['What is a Kafka topic?', 'A named stream of records split into partitions.', ['basics']],
    ['What is a partition?', 'An ordered append-only log segment that enables parallelism and ordering within the partition.', ['basics']],
    ['What is a consumer group?', 'A set of consumers sharing partitions so each partition is consumed by one group member at a time.', ['consumers']],
    ['What controls ordering?', 'Records with the same key go to the same partition, preserving order within that partition.', ['ordering']],
    ['What is consumer lag?', 'How far a consumer is behind the latest produced offset.', ['observability']],
    ['Why make consumers idempotent?', 'Kafka commonly provides at-least-once processing, so duplicates can happen.', ['reliability']],
    ['What is a DLQ?', 'A dead-letter queue/topic for messages that cannot be processed after retries.', ['reliability']],
    ['What is schema evolution?', 'Changing event structure while keeping producers and consumers compatible.', ['schemas']],
    ['When use Kafka over RabbitMQ?', 'When replay, high-throughput streams, durable logs and consumer-group scaling are central.', ['tradeoffs']],
    ['When might RabbitMQ be better?', 'For task queues, routing patterns and simpler command-style messaging.', ['tradeoffs']],
    ['What is the outbox pattern with Kafka?', 'Persist event records with business data, then publish them to Kafka asynchronously.', ['consistency']],
    ['What is compaction?', 'A topic retention mode that keeps the latest value per key.', ['storage']],
    ['How do you choose a partition key?', 'Use the key that matches ordering and load distribution requirements.', ['design']],
    ['What should you monitor?', 'Producer errors, consumer lag, throughput, processing latency, DLQ volume and broker health.', ['observability']],
    ['What is replay useful for?', 'Rebuilding projections, onboarding new consumers or recovering from consumer bugs.', ['replay']],
  ]),
  ...cards('Behavioral', [
    ['What does STAR stand for?', 'Situation, Task, Action, Result.', ['star']],
    ['What is the most important part of STAR?', 'Action and Result; they show what you did and why it mattered.', ['star']],
    ['How should you answer "why company"?', 'Use product-specific reasons, engineering fit and a real motivation signal.', ['motivation']],
    ['How do you discuss conflict?', 'Show respect, shared goals, trade-offs and resolution without blaming.', ['collaboration']],
    ['How do you discuss failure?', 'Own your part, explain learning and show concrete prevention steps.', ['ownership']],
    ['How do you keep answers concise?', 'Start with the headline, then give enough context and one concrete result.', ['communication']],
    ['What should you avoid in behavioral answers?', 'Vague teamwork, no personal action, no result and excessive company-confidential details.', ['pitfall']],
    ['How do you adapt stories by company?', 'Keep the core truth but emphasize the parts most relevant to the role and product.', ['strategy']],
    ['How should you discuss technical debt?', 'As a product risk/cost trade-off, not as aesthetic preference.', ['quality']],
    ['How do you show seniority?', 'Talk about ambiguity, trade-offs, communication, ownership and outcomes.', ['seniority']],
    ['How do you answer "ownership"?', 'Pick a story where you drove the outcome across implementation, communication and follow-up.', ['ownership']],
    ['How do you answer "speed vs quality"?', 'Separate non-negotiable correctness from scope that can be staged.', ['delivery']],
    ['How should you mention metrics?', 'Use measured numbers when known and label estimates honestly.', ['metrics']],
    ['How do you talk about learning Django?', 'Frame it as a targeted refresh from a strong Python/backend base.', ['django']],
    ['What is a good closing question?', 'Ask about current pain, success criteria or trade-offs the team is actively facing.', ['questions']],
  ]),
  ...cards('Company-specific', [
    ['What is Abacum?', 'An AI-native SaaS FP&A platform for planning, forecasting, data integration, reporting and finance decision-making.', ['abacum']],
    ['What is FP&A?', 'Financial planning and analysis: budgeting, forecasting, variance analysis and decision support.', ['finance']],
    ['What is actual vs forecast variance?', 'The difference between observed results and planned/forecasted values, often shown absolute and percentage.', ['finance']],
    ['Why is correctness critical for Abacum?', 'Finance teams use the data for decisions, reporting and planning; silent wrong numbers damage trust.', ['abacum']],
    ['What Django risk should Guillermo address?', 'Django is less recent than FastAPI, so he should refresh ORM, transactions, testing and app structure.', ['abacum']],
    ['What strength maps to Abacum integrations?', 'Experience with event-driven architecture, Kafka/RabbitMQ, AWS, PostgreSQL and high-throughput systems.', ['abacum']],
    ['What live coding themes are likely?', 'Aggregation, reconciliation, deduplication, validation, idempotency and dependency ordering.', ['abacum']],
    ['What system design theme is highly relevant?', 'A financial calculation engine with versioned inputs, async jobs and auditable result snapshots.', ['abacum']],
    ['What question should you ask Abacum about backend pain?', 'Which is more painful today: calculation correctness, performance, integrations or architecture evolution?', ['abacum']],
    ['How should Guillermo position FastAPI experience?', 'As transferable Python backend skill: clean services, validation, API design, testing and data access discipline.', ['abacum']],
    ['What finance vocabulary should be comfortable?', 'Actuals, forecast, budget, variance, reconciliation, audit trail, scenario and planning cycle.', ['finance']],
    ['What should not be overused in Abacum answers?', 'Distributed systems complexity when a simpler product-oriented design is enough.', ['judgment']],
    ['What is a strong 90-day success question?', 'What would success look like for this Backend Engineer after 90 days?', ['abacum']],
    ['How should AI experience be framed?', 'As pragmatic backend integration with permission-aware retrieval, evaluation and deterministic tools where needed.', ['abacum']],
    ['What is the first study priority for Abacum?', 'Python live coding on finance/SaaS data transformations, then Django ORM and SQL performance.', ['abacum']],
  ]),
]

export const flashcardGroups = Array.from(new Set(flashcards.map((card) => card.group)))
