import type { StudyPlanItem } from '../../types/content'

export const globalStudyPlan: StudyPlanItem[] = [
  {
    id: 'day-1-python-live-coding',
    day: 1,
    title: 'Python live coding baseline',
    module: 'Python live coding',
    companyBias: 'Abacum: finance/SaaS transformations',
    tasks: ['Solve aggregation by department/month.', 'Solve deduplication by source/external_id.', 'Explain complexity out loud after each solution.'],
    output: 'Three solved exercises with pytest-style edge cases.',
  },
  {
    id: 'day-2-django-orm',
    day: 2,
    title: 'Django ORM refresh',
    module: 'Django',
    companyBias: 'Abacum: reporting queries and N+1 avoidance',
    tasks: ['Review QuerySet laziness.', 'Compare select_related and prefetch_related.', 'Practice annotate, aggregate, F and Q examples.'],
    output: 'One-page Django ORM summary in your own words.',
  },
  {
    id: 'day-3-sql-postgres',
    day: 3,
    title: 'SQL/PostgreSQL performance',
    module: 'SQL/PostgreSQL',
    companyBias: 'Abacum: financial reporting and variance queries',
    tasks: ['Practice GROUP BY and joins.', 'Review composite indexes.', 'Explain EXPLAIN ANALYZE on a reporting query.'],
    output: 'Checklist for slow-query debugging.',
  },
  {
    id: 'day-4-testing-quality',
    day: 4,
    title: 'Testing backend business logic',
    module: 'Testing',
    companyBias: 'Abacum: calculation correctness',
    tasks: ['Prepare examples of unit vs integration tests.', 'Review pytest factories.', 'Design tests for permissions and recalculation jobs.'],
    output: 'Testing strategy answer for complex business logic.',
  },
  {
    id: 'day-5-system-design-finance',
    day: 5,
    title: 'System design for financial SaaS',
    module: 'System design',
    companyBias: 'Abacum: calculation engine, integrations and reporting',
    tasks: ['Design a calculation engine.', 'Design an integration pipeline.', 'Practice failure modes and observability.'],
    output: 'Two 10-minute system design walkthroughs.',
  },
  {
    id: 'day-6-behavioral-defense',
    day: 6,
    title: 'Behavioral and project defense',
    module: 'Behavioral interview',
    companyBias: 'Abacum: ownership, product engineering and architecture evolution',
    tasks: ['Prepare tell me about yourself.', 'Prepare RabbitMQ-to-Kafka story.', 'Prepare MCP/RAG and performance improvement stories.'],
    output: 'Four STAR stories with metrics/caveats clarified.',
  },
  {
    id: 'day-7-mock-and-polish',
    day: 7,
    title: 'Mock interview and polish',
    module: 'Mock interview mode',
    companyBias: 'Abacum: full process rehearsal',
    tasks: ['Run company-specific mock interview.', 'Review missed flashcards.', 'Finalize smart questions to ask.'],
    output: 'Final weak-area list and closing questions.',
  },
]
