import type { SystemDesignScenario } from '../../types/content'

export const systemDesignScenarios: SystemDesignScenario[] = [
  {
    id: 'financial-planning-calculation-engine',
    title: 'Design a financial planning calculation engine',
    tags: ['abacum', 'finance', 'calculation-engine'],
    requirements: [
      'Users define plans, scenarios, assumptions and formulas.',
      'Recalculate dependent line items when inputs change.',
      'Expose explainable results with version history.',
      'Support multi-tenant isolation and permission checks.',
    ],
    clarifyingQuestions: [
      'Are formulas user-defined or predefined by product?',
      'How fresh do results need to be: synchronous, near-real-time or batch?',
      'Do users need to audit why a number changed?',
      'What is the expected tenant size and formula graph complexity?',
    ],
    entities: ['Tenant', 'Plan', 'Scenario', 'LineItem', 'Formula', 'Assumption', 'CalculationRun', 'CalculationResult', 'AuditEvent'],
    apiDesign: [
      'POST /plans/{id}/inputs to update assumptions.',
      'POST /plans/{id}/recalculate to trigger a run.',
      'GET /plans/{id}/results?scenario=base&period=2026-Q1.',
      'GET /calculation-runs/{id} for status, errors and metadata.',
    ],
    architecture: [
      'HTTP API validates permissions and writes input changes transactionally.',
      'Dependency graph service topologically sorts affected formulas.',
      'Background workers run recalculation jobs and persist versioned results.',
      'Read API serves latest approved result snapshots with optional drill-down.',
    ],
    consistencyConcerns: [
      'Use versioned inputs so each run is reproducible.',
      'Keep input update, audit event and job enqueue tied with transaction.on_commit.',
      'Prevent concurrent runs from overwriting newer results.',
    ],
    scalingConcerns: [
      'Incremental recalculation for affected subgraphs.',
      'Partition large result tables by tenant or period if volume demands.',
      'Cache read-heavy snapshots with tenant-aware keys.',
    ],
    failureModes: [
      'Formula cycle detected.',
      'Worker crashes halfway through a run.',
      'External source data arrives late.',
      'User edits inputs while recalculation is running.',
    ],
    observability: [
      'Run duration, queue latency, formula error rate and affected line-item count.',
      'Structured logs with tenant, plan, run id and correlation id.',
      'Alerts for stuck runs and repeated formula failures.',
    ],
    tradeOffs: [
      'Synchronous recalculation is simpler but risks slow requests.',
      'Stored snapshots improve reads and auditability but need invalidation.',
      'User-defined formulas increase flexibility and validation complexity.',
    ],
    weakAnswer: 'I would just calculate values every time the dashboard loads and cache if it gets slow.',
    strongAnswer:
      'I would model plans, inputs and formula dependencies explicitly, version inputs, run recalculation asynchronously for non-trivial graphs, store reproducible result snapshots, and make failures/audit trails first-class.',
    finalSummaryAnswer:
      'The key is trust: deterministic versioned calculations, explicit dependency ordering, safe async execution, tenant isolation and observability around every run.',
  },
  {
    id: 'external-data-integration-pipeline',
    title: 'Design an external data integration pipeline',
    tags: ['abacum', 'integrations', 'etl'],
    requirements: [
      'Import data from ERP, CRM and HRIS systems.',
      'Normalize inconsistent schemas into internal financial records.',
      'Deduplicate and retry safely.',
      'Show sync status and errors to users.',
    ],
    clarifyingQuestions: [
      'Push webhooks, polling, or both?',
      'What are the rate limits and data volumes?',
      'Are updates incremental or full syncs?',
      'How should conflicts be resolved?',
    ],
    entities: ['Integration', 'SyncRun', 'ExternalRecord', 'NormalizedRecord', 'SchemaMapping', 'ImportError', 'IdempotencyKey'],
    apiDesign: [
      'POST /integrations/{id}/sync to trigger manual sync.',
      'GET /integrations/{id}/status for last success and current run.',
      'POST /webhooks/{provider} for provider events.',
      'GET /sync-runs/{id}/errors for actionable row-level feedback.',
    ],
    architecture: [
      'Connector layer fetches raw data and stores immutable raw payloads.',
      'Normalizer maps external fields to typed internal records.',
      'Validation emits row-level errors without dropping the whole batch unnecessarily.',
      'Idempotent upsert layer uses tenant + source + external_id constraints.',
    ],
    consistencyConcerns: [
      'Use idempotency keys for retries.',
      'Keep raw payloads for replay and debugging.',
      'Mark sync success only after normalized records commit.',
    ],
    scalingConcerns: [
      'Chunk large imports.',
      'Respect provider rate limits with backoff.',
      'Parallelize by tenant or data category where safe.',
    ],
    failureModes: [
      'Provider API outage.',
      'Schema drift from external system.',
      'Partial batch failure.',
      'Duplicate webhook delivery.',
    ],
    observability: [
      'Sync duration, rows imported, validation errors, provider latency and retry counts.',
      'Dead-letter queue for poison records.',
      'Customer-visible status with last successful sync timestamp.',
    ],
    tradeOffs: [
      'Storing raw payloads costs space but improves replayability.',
      'Strict validation protects quality but may block useful partial imports.',
      'Polling is predictable; webhooks are fresher but less controllable.',
    ],
    weakAnswer: 'I would call the external API, transform the JSON and save it.',
    strongAnswer:
      'I would separate extraction, raw storage, normalization, validation and idempotent upsert, with sync-run state, retries, provider rate-limit handling and user-visible errors.',
    finalSummaryAnswer:
      'A strong integration pipeline is boring in the best way: replayable, idempotent, observable and honest about partial failures.',
  },
  {
    id: 'multi-tenant-reporting-api',
    title: 'Design a multi-tenant reporting API',
    tags: ['abacum', 'reporting', 'saas'],
    requirements: [
      'Serve financial reports filtered by tenant, period, scenario and department.',
      'Support pagination and exports.',
      'Prevent cross-tenant leakage.',
      'Keep dashboard latency low.',
    ],
    clarifyingQuestions: [
      'How large can reports be?',
      'Do users require real-time results or accepted staleness?',
      'Are reports ad hoc or based on predefined dimensions?',
      'What permissions apply at department or scenario level?',
    ],
    entities: ['Tenant', 'User', 'Report', 'Metric', 'Dimension', 'ReportSnapshot', 'Permission', 'ExportJob'],
    apiDesign: [
      'GET /reports/{id}?period=2026-Q1&scenario=base.',
      'GET /reports/{id}/rows?cursor=...',
      'POST /reports/{id}/exports for async export.',
      'GET /exports/{id} for export status and download URL.',
    ],
    architecture: [
      'API always scopes queries by tenant from auth context.',
      'Read model stores precomputed report rows for common dashboards.',
      'Ad hoc filters use indexed fact tables and bounded query constraints.',
      'Large exports run asynchronously and stream from object storage.',
    ],
    consistencyConcerns: [
      'Include data freshness timestamp.',
      'Use snapshot versions for reports shown in meetings.',
      'Avoid mixing draft and approved data accidentally.',
    ],
    scalingConcerns: [
      'Keyset pagination for row lists.',
      'Materialized views or summary tables for repeated aggregations.',
      'Tenant-aware cache keys and invalidation on input changes.',
    ],
    failureModes: ['Slow unbounded queries.', 'Permission leak through filters.', 'Export job timeout.', 'Stale cached data shown as fresh.'],
    observability: ['P95 latency per report type.', 'Slow query logs by tenant and endpoint.', 'Cache hit rate and export job failures.'],
    tradeOffs: ['Precomputation improves speed but adds freshness complexity.', 'Flexible ad hoc reporting increases query risk.', 'Async exports improve reliability but add UX steps.'],
    weakAnswer: 'I would create one endpoint that queries all report data with filters.',
    strongAnswer:
      'I would enforce tenant scoping at every query boundary, define bounded report APIs, precompute common snapshots, make exports async and surface data freshness.',
    finalSummaryAnswer:
      'The reporting API should optimize for trust, speed and isolation: tenant-scoped access, indexed filters, precomputed snapshots and honest freshness metadata.',
  },
  {
    id: 'audit-logs-financial-changes',
    title: 'Design audit logs for financial changes',
    tags: ['finance', 'audit', 'compliance'],
    requirements: [
      'Track who changed financial data, when and why.',
      'Support investigation and customer-facing history.',
      'Protect audit records from modification.',
      'Correlate changes across API, jobs and integrations.',
    ],
    clarifyingQuestions: [
      'Which entities require audit: budgets, assumptions, imports, permissions?',
      'Do customers view the audit log?',
      'Retention period?',
      'Need before/after values or event-style facts?',
    ],
    entities: ['AuditEvent', 'Actor', 'Tenant', 'EntityRef', 'ChangeSet', 'CorrelationId', 'RequestMetadata'],
    apiDesign: [
      'GET /audit-events?entity_type=budget&entity_id=...',
      'GET /audit-events?actor_id=...&from=...&to=...',
      'POST is avoided for public clients; audit creation is internal to write paths.',
    ],
    architecture: [
      'Write audit events in the same transaction as the business change.',
      'Append-only audit table with strict permissions.',
      'Correlation id propagated from request/job to all writes.',
      'Optional event stream for analytics or external compliance export.',
    ],
    consistencyConcerns: [
      'Audit event should not exist without the business change or vice versa.',
      'Use immutable records; corrections are new audit events.',
      'Capture actor type: user, system job or integration.',
    ],
    scalingConcerns: [
      'Partition by tenant or time for large volume.',
      'Keyset pagination.',
      'Archive cold audit logs to cheaper storage if retention is long.',
    ],
    failureModes: ['Audit write failure blocks business write.', 'Sensitive data leaked in diffs.', 'Missing audit for background jobs.'],
    observability: ['Audit write failures.', 'Events per entity type.', 'Gaps between business writes and audit events.'],
    tradeOffs: ['Before/after diffs are easy to read but can leak sensitive data.', 'Event-sourcing is powerful but heavier than needed for simple audit.', 'Blocking on audit improves trust but can reduce availability.'],
    weakAnswer: 'I would log changes in application logs.',
    strongAnswer:
      'I would use append-only structured audit events written transactionally with business changes, with actor, tenant, entity, correlation id, before/after summary and careful access controls.',
    finalSummaryAnswer:
      'Audit logging is product data, not debug logging: append-only, queryable, permissioned and transactionally tied to the change.',
  },
  {
    id: 'forecast-recalculation-jobs',
    title: 'Design a background job system for recalculating forecasts',
    tags: ['jobs', 'finance', 'reliability'],
    requirements: [
      'Trigger recalculation after input changes or scheduled imports.',
      'Retry transient failures.',
      'Avoid duplicate or stale runs.',
      'Expose progress to users.',
    ],
    clarifyingQuestions: ['How long can a recalculation take?', 'Can runs be cancelled?', 'Is freshness more important than cost?', 'Are results tenant-isolated?'],
    entities: ['Job', 'JobAttempt', 'Plan', 'InputVersion', 'ResultVersion', 'QueueMessage', 'Worker'],
    apiDesign: ['POST /plans/{id}/recalculate', 'GET /jobs/{id}', 'POST /jobs/{id}/cancel'],
    architecture: [
      'API creates a calculation run record and enqueues after commit.',
      'Workers claim jobs, validate input version, execute formulas and persist results.',
      'Deduplicate by tenant + plan + input_version where appropriate.',
      'Job state machine: queued, running, succeeded, failed, cancelled.',
    ],
    consistencyConcerns: ['Never publish success before results commit.', 'Discard stale run results if a newer input version exists.', 'Use idempotent job handlers.'],
    scalingConcerns: ['Queue partitioning by tenant or plan.', 'Worker autoscaling based on queue latency.', 'Chunk large plans by dependency layers.'],
    failureModes: ['Worker death after partial writes.', 'Retry storm.', 'Poison formula input.', 'Concurrent recalculation of same plan.'],
    observability: ['Queue latency, run duration, retries, failure reason, stale runs skipped.', 'Per-tenant job volume.'],
    tradeOffs: ['Single job is simpler; chunked graph jobs improve scale but complicate consistency.', 'At-least-once queues require idempotency.', 'Cancelling jobs is useful but adds state complexity.'],
    weakAnswer: 'I would put recalculation in a Celery task and retry it.',
    strongAnswer:
      'I would design an idempotent job state machine tied to input versions, enqueue after commit, handle retries and stale runs explicitly, and make progress visible to users.',
    finalSummaryAnswer:
      'The core is versioned idempotency: a job recalculates a known input version, commits a known result version and can be retried safely.',
  },
  {
    id: 'finance-permissions-model',
    title: 'Design a permissions model for finance teams',
    tags: ['security', 'saas', 'finance'],
    requirements: [
      'Support tenant-level roles and department-level access.',
      'Restrict sensitive plans, scenarios and reports.',
      'Allow admins to manage users.',
      'Audit permission changes.',
    ],
    clarifyingQuestions: ['RBAC enough, or need attribute-based rules?', 'Can users belong to multiple departments?', 'Do permissions inherit through org hierarchy?', 'Are external auditors read-only?'],
    entities: ['Tenant', 'User', 'Role', 'Permission', 'Department', 'Resource', 'Membership', 'Policy', 'AuditEvent'],
    apiDesign: ['GET /me/permissions', 'POST /users/{id}/roles', 'GET /reports/{id} with object-level authorization'],
    architecture: [
      'RBAC for broad capabilities such as admin, manager and viewer.',
      'Resource scoping by tenant and department.',
      'Object-level checks in service/query layer.',
      'Permission changes written with audit events.',
    ],
    consistencyConcerns: ['Deny by default.', 'Tenant filter before object access.', 'Invalidate permission cache after changes.'],
    scalingConcerns: ['Cache computed permissions per user/tenant with short TTL.', 'Use indexed membership tables.', 'Avoid per-row policy checks in huge reports when a scoped query can enforce access.'],
    failureModes: ['Cross-tenant access through direct id lookup.', 'Stale permission cache.', 'Admin grants not audited.'],
    observability: ['Authorization denials by endpoint.', 'Permission change audit events.', 'Suspicious cross-tenant lookup attempts.'],
    tradeOffs: ['RBAC is simple but less flexible.', 'ABAC is expressive but harder to explain and test.', 'Database row-level security can help but adds operational complexity.'],
    weakAnswer: 'I would add a role column on the user table.',
    strongAnswer:
      'I would combine tenant-scoped RBAC with department/object constraints, enforce permissions in queries and services, deny by default and audit all permission changes.',
    finalSummaryAnswer:
      'For finance teams, permission design is a data-isolation feature: tenant scoping, object checks, clear roles and auditability.',
  },
  {
    id: 'kafka-event-driven-workflow',
    title: 'Design a Kafka-based event-driven workflow',
    tags: ['kafka', 'event-driven', 'backend'],
    requirements: [
      'Publish events when financial records change.',
      'Consumers update projections, audit streams and notifications.',
      'Handle retries and ordering where needed.',
      'Support replay for new consumers.',
    ],
    clarifyingQuestions: ['What ordering guarantees are needed?', 'Expected throughput?', 'Can consumers be eventually consistent?', 'What is the event retention requirement?'],
    entities: ['Topic', 'Event', 'Producer', 'ConsumerGroup', 'Schema', 'OutboxRecord', 'Projection'],
    apiDesign: ['Events such as FinancialRecordImported, ForecastRecalculated, PermissionChanged.', 'Internal admin endpoint to replay from offset for a projection.'],
    architecture: [
      'Transactional outbox writes events with business changes.',
      'Publisher relays outbox rows to Kafka.',
      'Topics partition by tenant or aggregate id depending on ordering needs.',
      'Consumers are idempotent and track offsets through Kafka consumer groups.',
    ],
    consistencyConcerns: ['Avoid dual-write bug with outbox.', 'Schema evolution with compatibility rules.', 'Idempotent consumers for at-least-once delivery.'],
    scalingConcerns: ['Partition count for parallelism.', 'Consumer lag monitoring.', 'Backpressure and dead-letter handling.'],
    failureModes: ['Poison message blocks partition.', 'Consumer lag grows.', 'Schema-incompatible event breaks consumers.', 'Duplicate delivery.'],
    observability: ['Producer error rate, consumer lag, DLQ counts, event age, schema version usage.'],
    tradeOffs: ['Kafka improves decoupling and replay but adds operational complexity.', 'Strong ordering reduces parallelism.', 'Outbox adds table/process overhead but protects consistency.'],
    weakAnswer: 'I would send a Kafka message after saving to the database.',
    strongAnswer:
      'I would use a transactional outbox, partition according to ordering needs, version event schemas, make consumers idempotent and monitor lag/dead letters.',
    finalSummaryAnswer:
      'A good Kafka design starts with delivery semantics: outbox for consistency, partitions for ordering, idempotent consumers and observable lag.',
  },
  {
    id: 'llm-rag-business-data',
    title: 'Design an LLM/RAG assistant for internal business data',
    tags: ['rag', 'llm', 'aws', 'abacum'],
    requirements: [
      'Answer questions over internal business and financial data.',
      'Respect tenant and user permissions.',
      'Cite sources and avoid unsupported claims.',
      'Handle sensitive data safely.',
    ],
    clarifyingQuestions: ['Is the assistant customer-facing or internal?', 'What data sources are in scope?', 'What latency and accuracy expectations exist?', 'Need deterministic calculations or narrative explanations?'],
    entities: ['Document', 'Embedding', 'Chunk', 'PermissionScope', 'Query', 'Answer', 'Citation', 'Feedback'],
    apiDesign: ['POST /assistant/query with question and context.', 'GET /assistant/answers/{id} for answer, citations and feedback state.'],
    architecture: [
      'Ingestion pipeline chunks documents and stores embeddings with tenant and permission metadata.',
      'Retriever filters by permissions before vector search or applies secure post-filtering with strict checks.',
      'Prompt includes retrieved context, system rules and citation requirement.',
      'For numeric finance answers, call deterministic tools/calculation APIs instead of relying only on generation.',
    ],
    consistencyConcerns: ['Keep index in sync with source permissions.', 'Do not expose deleted or revoked documents.', 'Separate raw model output from verified answer state.'],
    scalingConcerns: ['Batch embeddings.', 'Cache safe retrieval results cautiously.', 'Use async ingestion and re-indexing jobs.'],
    failureModes: ['Hallucinated answer.', 'Permission leak through retrieval.', 'Stale embeddings.', 'Prompt injection in source documents.'],
    observability: ['Retrieval hit rate, citation coverage, refusal rate, latency, feedback, permission-denied attempts.'],
    tradeOffs: ['RAG improves grounding but not deterministic truth.', 'Fine-grained permissions complicate retrieval.', 'Tool calls improve numeric accuracy but add orchestration.'],
    weakAnswer: 'I would put company documents in a vector database and ask the LLM.',
    strongAnswer:
      'I would build permission-aware ingestion and retrieval, require citations, use deterministic tools for calculations, guard against prompt injection and monitor answer quality.',
    finalSummaryAnswer:
      'The assistant must be secure before it is clever: permission-aware retrieval, cited answers and deterministic calculation tools for finance questions.',
  },
  {
    id: 'high-throughput-api-caching',
    title: 'Design a high-throughput API with caching',
    tags: ['api', 'caching', 'performance'],
    requirements: [
      'Serve read-heavy endpoints with low latency.',
      'Keep cache correct across tenant and permission boundaries.',
      'Handle spikes and provider slowness.',
      'Expose predictable API behavior.',
    ],
    clarifyingQuestions: ['Which endpoints are read-heavy?', 'Can data be stale?', 'What invalidates cached data?', 'Are responses user-specific?'],
    entities: ['CacheKey', 'Tenant', 'UserPermission', 'ResponseSnapshot', 'InvalidationEvent', 'RateLimit'],
    apiDesign: ['GET /reports/{id}/summary with ETag.', 'GET /metrics with cache-control based on freshness SLA.'],
    architecture: [
      'Application cache for computed summaries.',
      'CDN or edge cache only for safe non-user-specific resources.',
      'Tenant/user-aware cache keys.',
      'Invalidation on write events or short TTL depending on freshness requirements.',
    ],
    consistencyConcerns: ['Avoid serving one user another user permission-filtered data.', 'Expose freshness metadata.', 'Use stale-while-revalidate only where acceptable.'],
    scalingConcerns: ['Cache stampede protection.', 'Request coalescing.', 'Database read replicas for safe read load.', 'Rate limits for abusive clients.'],
    failureModes: ['Cache stampede after invalidation.', 'Stale critical finance data.', 'Hot tenant overload.', 'Incorrect cache key leaks data.'],
    observability: ['Cache hit rate, origin latency, stampede events, per-tenant throughput, error budget.'],
    tradeOffs: ['Long TTL improves speed but risks staleness.', 'Fine-grained keys are safer but reduce hit rate.', 'Precomputation adds write-side complexity.'],
    weakAnswer: 'I would add Redis in front of the database.',
    strongAnswer:
      'I would cache only well-defined read models with tenant/permission-aware keys, clear freshness semantics, stampede protection, metrics and invalidation tied to writes.',
    finalSummaryAnswer:
      'Caching is a correctness feature as much as a speed feature: keys, freshness and invalidation matter more than the cache technology.',
  },
  {
    id: 'rabbitmq-to-kafka-migration',
    title: 'Design a migration from RabbitMQ to Kafka',
    tags: ['kafka', 'rabbitmq', 'migration', 'cv-defense'],
    requirements: [
      'Move event streaming from RabbitMQ to Kafka without downtime.',
      'Preserve critical consumers and delivery semantics.',
      'Measure throughput and lag.',
      'Roll back safely if needed.',
    ],
    clarifyingQuestions: ['Why migrate: throughput, replay, ordering, ecosystem?', 'How many producers/consumers?', 'Can consumers tolerate duplicates?', 'Which events require strict ordering?'],
    entities: ['Producer', 'RabbitMQExchange', 'KafkaTopic', 'Consumer', 'Bridge', 'Schema', 'Offset', 'DLQ'],
    apiDesign: ['Internal producer abstraction publish(event).', 'Consumer adapter per event type.', 'Operational endpoints for lag and migration state.'],
    architecture: [
      'Introduce event schema and producer abstraction.',
      'Dual-publish or bridge from RabbitMQ to Kafka during transition.',
      'Move low-risk consumers first and compare outputs.',
      'Make consumers idempotent before cutover.',
      'Monitor lag, error rate and throughput throughout rollout.',
    ],
    consistencyConcerns: ['Duplicates during dual-publish.', 'Ordering changes by partition key.', 'Schema compatibility between old and new consumers.'],
    scalingConcerns: ['Partition strategy for parallelism.', 'Consumer group sizing.', 'Backpressure if downstream is slower than Kafka input.'],
    failureModes: ['Bridge drops messages.', 'Consumer offset mismanagement.', 'Poison messages.', 'Rollback with diverged state.'],
    observability: ['Rabbit queue depth, Kafka consumer lag, publish errors, DLQ volume, end-to-end processing latency.'],
    tradeOffs: ['Dual-publish gives control but risks duplicate side effects.', 'Bridge is faster to adopt but may hide semantics.', 'Kafka replay is powerful but demands idempotent consumers.'],
    weakAnswer: 'I would replace RabbitMQ publishing with Kafka publishing and deploy it.',
    strongAnswer:
      'I would migrate incrementally with a producer abstraction, schemas, dual-run/bridge phase, idempotent consumers, topic partition strategy, lag monitoring and a rollback plan.',
    finalSummaryAnswer:
      'The winning migration answer is controlled risk: abstractions, compatibility, dual-run validation, idempotency, observability and staged cutover.',
  },
]
