import type { CompanyProfile } from '../../types/company'

export const abacum: CompanyProfile = {
  id: 'abacum',
  name: 'Abacum',
  website: 'https://www.abacum.ai/',
  roleTitle: 'Backend Engineer',
  location: 'Spain',
  workMode: 'Remote within Spain',
  salaryRange: '65-70K EUR base salary range can be considered',
  equity: 'Equity plan included',
  recruiterNotes: [
    'Expected agile process of roughly 2-3 weeks.',
    'Online technical challenge around one hour before deeper technical conversations.',
    'Backend role centered on Python, Django, product engineering, ownership and complex business logic.',
  ],
  companySummary:
    'Abacum is an AI-native SaaS FP&A platform that helps finance teams plan, forecast, integrate data, report and make decisions faster with real-time data. It replaces manual spreadsheet-heavy finance processes with a centralized, automated and scalable planning system.',
  productSummary: [
    'Financial planning and budgeting workflows.',
    'Continuous forecasting and variance analysis.',
    'Data integration from finance, CRM, HRIS and operational systems.',
    'Reporting dashboards and centralized financial decision-making.',
    'AI-assisted workflows for finance teams that need speed without losing trust.',
  ],
  domain: ['SaaS', 'FP&A', 'Fintech-adjacent', 'B2B', 'AI-native finance tooling'],
  businessModel: 'B2B SaaS sold to finance teams and leadership teams that need collaborative planning, forecasting and reporting.',
  funding: 'Founded in 2020 by two former CFOs. Raised over $100M, including a $60M Series B in June 2025 led by Scale Venture Partners.',
  teamSize: '100+ people from 30+ nationalities',
  offices: ['New York', 'London', 'Barcelona'],
  processStages: [
    {
      id: 'challenge',
      title: 'Online technical challenge',
      format: 'Timed coding exercise',
      duration: 'Around 1 hour',
      focus: ['Python fluency', 'Data transformation', 'Correctness under time pressure', 'Tests and edge cases'],
      preparation: [
        'Practice compact Python solutions with dictionaries, grouping and validation.',
        'Narrate assumptions before coding: input size, malformed rows, duplicated IDs and rounding.',
        'Leave time for tests and a complexity statement.',
      ],
    },
    {
      id: 'manager',
      title: 'Manager interview',
      format: 'Role fit and ownership conversation',
      focus: ['Product mindset', 'Team fit', 'Autonomy', 'Working with ambiguity'],
      preparation: [
        'Prepare a crisp story about building backend features with product impact.',
        'Map your FastAPI strengths to Django and product SaaS delivery.',
        'Ask about squad ownership, release cadence and quality bar.',
      ],
    },
    {
      id: 'live-coding',
      title: 'Live coding with technical team',
      format: 'Collaborative problem solving',
      focus: ['Python', 'Backend data structures', 'Communication', 'Testing approach'],
      preparation: [
        'Practice finance-flavored aggregation, reconciliation and deduplication exercises.',
        'Explain trade-offs before optimizing.',
        'Use small helper functions and make edge cases visible.',
      ],
    },
    {
      id: 'final',
      title: 'Final CTO/founder interview',
      format: 'Technical leadership, company fit and product judgment',
      focus: ['Ownership', 'Architecture evolution', 'Business context', 'Motivation'],
      preparation: [
        'Prepare why FP&A infrastructure is interesting to you.',
        'Prepare two thoughtful product/architecture questions.',
        'Be ready to discuss technical debt, reliability and scaling in a growing company.',
      ],
    },
  ],
  requiredStack: [
    'Python',
    'Django',
    'Backend engineering',
    'Product background',
    'Complex systems',
    'Testing',
    'Clean code',
    'Performance',
    'Architecture',
  ],
  preferredStack: ['PostgreSQL', 'AWS', 'Event-driven architecture', 'Observability', 'Kubernetes', 'Data integrations'],
  roleResponsibilities: [
    'Build backend product features inside small autonomous squads.',
    'Model and evolve complex business logic for finance workflows.',
    'Improve platform reliability, performance and scalability.',
    'Make technical decisions with enough ownership to influence architecture.',
    'Work closely with product and finance-domain stakeholders.',
  ],
  likelyTechnicalChallenges: [
    'Real-time calculations where correctness and trust matter more than cleverness.',
    'Data integration pipelines with inconsistent external schemas and stale data.',
    'Performance-sensitive reporting and aggregation over financial records.',
    'Multi-tenant permissions and safe access to sensitive finance data.',
    'Architecture evolution while the company grows quickly.',
  ],
  interviewFocusAreas: [
    'Python live coding on dictionaries, grouping, sorting, validation and idempotency.',
    'Django ORM fluency: relationships, query optimization, transactions and tests.',
    'PostgreSQL performance and data modeling for financial SaaS.',
    'System design for calculation engines, reporting APIs and integration pipelines.',
    'Behavioral ownership stories with product impact.',
  ],
  riskAreasForCandidate: [
    'Django experience is present but less recent than FastAPI; refresh ORM, migrations, transactions and testing idioms.',
    'Finance-domain language may be unfamiliar; practice explaining actuals, forecast, variance, budget, reconciliation and auditability.',
    'Live coding under time pressure needs rehearsed communication and test-first habits.',
    'Avoid over-indexing on distributed systems when a simpler product-oriented design is enough.',
  ],
  candidateStrengthsForThisRole: [
    '5+ years of backend engineering with strong Python and FastAPI.',
    'Microservices, event-driven architecture, Kafka, RabbitMQ and high-throughput platform experience.',
    'AWS, PostgreSQL, Kubernetes, Docker, Helm, GitLab CI/CD and observability exposure.',
    'RabbitMQ-to-Kafka migration story maps well to integration and architecture evolution.',
    'MCP/RAG and AWS Bedrock work is relevant to AI-native product direction.',
  ],
  preparationPriorities: [
    'Python live coding with finance/SaaS data transformation exercises.',
    'Django ORM, transactions, testing and performance refresh.',
    'SQL/PostgreSQL aggregation, indexes, locking and query plans.',
    'System design for financial SaaS calculation, reporting, integrations and auditability.',
    'Behavioral and CV defense stories tied to product ownership and measurable impact.',
  ],
  likelyQuestions: [
    'How would you design a system that recalculates financial forecasts when source data changes?',
    'What is the difference between select_related and prefetch_related in Django?',
    'How do you avoid duplicate records when ingesting data from external systems?',
    'Tell me about a technical decision you led and what trade-offs you considered.',
    'How would you model permissions for finance teams across departments and subsidiaries?',
    'How do you test complex business logic without making tests brittle?',
    'Why Abacum, and why backend product engineering now?',
  ],
  smartQuestionsToAsk: [
    'Which backend problems are currently most painful: calculation correctness, performance, integrations, or architecture evolution?',
    'How do squads balance speed with the trust requirements of financial data?',
    'Where does the team draw the boundary between Django models, services and asynchronous jobs?',
    'What kinds of customer data volumes or tenant sizes stress the platform today?',
    'How is AI being introduced into workflows while keeping finance users confident in the output?',
    'What would success look like for this Backend Engineer after 90 days?',
  ],
  systemDesignScenarios: [
    'Design a financial planning calculation engine.',
    'Design an external data integration pipeline.',
    'Design a multi-tenant reporting API.',
    'Design audit logs for financial changes.',
    'Design a background job system for recalculating forecasts.',
    'Design a permissions model for finance teams.',
  ],
  liveCodingThemes: [
    'Aggregate transactions by department and month.',
    'Compute actual vs forecast variance.',
    'Deduplicate external financial records.',
    'Normalize external field names.',
    'Implement idempotency keys for ingestion.',
    'Top N departments by spend.',
  ],
  behavioralThemes: [
    'Ownership in ambiguous product contexts.',
    'Leading a technical decision.',
    'Explaining a migration from RabbitMQ to Kafka.',
    'Working with product on trade-offs.',
    'Improving performance without sacrificing maintainability.',
    'Learning Django-specific details quickly from a FastAPI base.',
  ],
  studyPlan: [
    {
      day: 1,
      title: 'Python finance transformations',
      focus: 'Live coding speed and communication',
      tasks: [
        'Solve three aggregation/reconciliation exercises out loud.',
        'Write pytest cases before final cleanup.',
        'Practice a 30-second complexity summary.',
      ],
    },
    {
      day: 2,
      title: 'Django ORM core',
      focus: 'Django readiness',
      tasks: [
        'Review models, migrations, QuerySets, select_related and prefetch_related.',
        'Explain where business logic should live in a Django product codebase.',
        'Write notes on transaction.atomic and constraints.',
      ],
    },
    {
      day: 3,
      title: 'SQL and PostgreSQL performance',
      focus: 'Financial reporting queries',
      tasks: [
        'Practice GROUP BY, joins, composite indexes and EXPLAIN ANALYZE.',
        'Prepare examples for N+1, pagination and materialized views.',
        'Define how to store financial calculation results and audit trails.',
      ],
    },
    {
      day: 4,
      title: 'System design for FP&A SaaS',
      focus: 'Calculation engine and integrations',
      tasks: [
        'Design a recalculation job system.',
        'Design a multi-tenant reporting API.',
        'Prepare trade-offs: sync vs async, cached vs fresh, normalized vs denormalized.',
      ],
    },
    {
      day: 5,
      title: 'Behavioral and CV defense',
      focus: 'Manager/founder readiness',
      tasks: [
        'Prepare RabbitMQ-to-Kafka STAR story.',
        'Prepare MCP/RAG and AWS Bedrock defense.',
        'Draft Abacum-specific motivation and closing questions.',
      ],
    },
  ],
  fitAnalysis: [
    'Strong fit on Python backend, complex systems, event-driven thinking, AWS/PostgreSQL and ownership.',
    'The role rewards product judgment, not only infrastructure depth; Guillermo should frame technical work through customer and finance-team outcomes.',
    'FastAPI experience transfers well if he can show Django fluency in ORM, transactions, app structure and testing.',
  ],
  whyAttractive: [
    'The product has real backend depth: calculation correctness, integrations, reporting performance, permissions and auditability.',
    'Abacum is scaling after significant funding, so backend engineers can influence architecture while still shipping product.',
    "AI-native finance tooling connects well with Guillermo's MCP/RAG and AWS Bedrock experience.",
    'Remote within Spain plus Barcelona presence fits the location constraint.',
  ],
  studyFirst: [
    'Python live coding on business-data transformations.',
    'Django ORM and transaction refresh.',
    'SQL aggregation and query-plan performance.',
    'FP&A vocabulary: actuals, forecast, variance, budget, reconciliation, audit trail.',
  ],
  interviewStrategy: [
    'Position yourself as a product backend engineer who can also scale systems when needed.',
    'When asked about architecture, start with correctness and domain clarity before Kafka or infrastructure.',
    'Use the Kafka migration and MCP/RAG stories as proof of ownership, but tie them to user or business value.',
    'For live coding, clarify data shape, edge cases, rounding, duplicates and malformed rows before implementation.',
  ],
  djangoPrepChecklist: [
    'Explain Django request lifecycle from URL resolver to middleware, view, ORM and response.',
    'Know model fields, migrations, constraints and indexes.',
    'Compare select_related and prefetch_related with concrete query examples.',
    'Use annotate, aggregate, F expressions and Q objects naturally.',
    'Explain transaction.atomic, select_for_update and idempotent writes.',
    'Describe testing with pytest, factories and query-count checks.',
    'Know why signals are easy to misuse and when a service layer is clearer.',
  ],
  sqlPerformanceChecklist: [
    'Read EXPLAIN ANALYZE for sequential scans, nested loops and index usage.',
    'Choose composite index order based on filters, joins and ordering.',
    'Avoid offset pagination for deep pages; use keyset pagination where possible.',
    'Understand GROUP BY, date truncation, materialized views and denormalized read models.',
    'Use transactions and row-level locks for financial consistency.',
    'Keep auditability: immutable events, who/when/why metadata and reconciliation checks.',
  ],
  notes: [
    'Refresh Django enough to sound current, not apologetic.',
    'Bring finance-domain examples into every technical answer where natural.',
    'Use concise stories with metrics, but clearly separate measured facts from estimates.',
  ],
}
