import type { CompanyProfile } from '../../types/company'

export const exampleCompany: CompanyProfile = {
  id: 'example-company',
  name: 'Example Company',
  website: 'https://example.com',
  roleTitle: 'Backend Engineer',
  location: 'Remote',
  workMode: 'Remote',
  salaryRange: 'Add range if known',
  equity: 'Add equity details if known',
  recruiterNotes: ['Use this file as a copyable template for a new process.'],
  companySummary: 'Short company summary.',
  productSummary: ['Product line or workflow one.', 'Product line or workflow two.'],
  domain: ['SaaS'],
  businessModel: 'Describe who pays and why.',
  funding: 'Funding or company stage.',
  teamSize: 'Team size if known.',
  offices: ['Remote'],
  processStages: [],
  requiredStack: ['Python'],
  preferredStack: ['PostgreSQL'],
  roleResponsibilities: ['Describe the work.'],
  likelyTechnicalChallenges: ['Describe probable challenge.'],
  interviewFocusAreas: ['Describe focus area.'],
  riskAreasForCandidate: ['Describe gaps to prepare.'],
  candidateStrengthsForThisRole: ['Describe matching strengths.'],
  preparationPriorities: ['Describe priority.'],
  likelyQuestions: ['Question to prepare.'],
  smartQuestionsToAsk: ['Question to ask the company.'],
  systemDesignScenarios: ['Relevant design scenario.'],
  liveCodingThemes: ['Relevant coding theme.'],
  behavioralThemes: ['Relevant behavioral theme.'],
  studyPlan: [],
  fitAnalysis: ['Summarize fit.'],
  whyAttractive: ['Why the role is attractive.'],
  studyFirst: ['First topic to study.'],
  interviewStrategy: ['How to position yourself.'],
  djangoPrepChecklist: ['Django topic if relevant.'],
  sqlPerformanceChecklist: ['SQL topic if relevant.'],
  notes: ['Free-form notes.'],
}
